version: '3.8'
services:
  devcontainer:
    container_name: devcontainer
    build:
      context: ..
      dockerfile: .devcontainer/shell-container/Dockerfile
    command: /home/vscode/container-start-script.sh
    volumes:
      - ../..:/workspaces:cached
      - ~/.gitconfig:/home/vscode/.gitconfig
